name: CI/CD Pipeline

on:
  push:
    branches: [ 22-cicd ]
  pull_request:
    branches: [ 22-cicd ]

jobs:
  docker:
    uses: Xenon-Lang-Org/Glados-image/.github/docker/docker-build.yml@main
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
    secrets:
      PAT: ${{ secrets.GH_PAT }}
      REGISTRY_USERNAME: ${{ github.actor }}
      REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}